### ISSUE TITLE
EppoClient and/or InMemoryAssignmentCache should be thread safe

### ISSUE THREAD

**Issue by jonstaff** [Eppo-exp/eppo-ios-sdk#30]
It's currently possible to get an `EXC_BAD_ACCESS` crash when using `EppoClient` in a multithreaded environment. Clients that use the SDK can prevent this by implementing their own thread safe measures, but it should probably also be done inside the SDK.

**Comment by leoromanovsky** [comment]
Thank you @jonstaff for the report and the test case - I am able to reproduce it on tag `v1.2.0`.

> It's currently possible to get an `EXC_BAD_ACCESS` crash when using `EppoClient` in a multithreaded environment. Clients that use the SDK can prevent this by implementing their own thread safe measures, but it should probably also be done inside the SDK.

Do you mean instantiating the SDK or some other operation? I will investigate in parallel in the meantime.

**Comment by leoromanovsky** [comment]
Demonstrated that catching the exception and moving the `load` outside the loop resolved the reported issue:

```
Task {
      try await eppoClient.load()
      await withThrowingTaskGroup(of: Void.self) { group in
        for i in 0 ..< expectedCount {
          group.addTask {
              print("start \(i)")
              //try await eppoClient.load()
              do {
                let assignment = try eppoClient.getAssignment("subject_key", "unused-allocation-test", [:])
              } catch (let e) {
                  print(e)
              }
              print("end \(i)")
              expectation.fulfill()
          }
        }
      }
    }
```
